# Generated by Django 5.2.5 on 2025-12-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinward',
            old_name='faculty_name',
            new_name='pi_name',
        ),
        migrations.RenameField(
            model_name='fundrequest',
            old_name='faculty_name',
            new_name='pi_name',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='faculty_name',
            new_name='pi_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pi',
            new_name='pi_name',
        ),
        migrations.RenameField(
            model_name='seedgrant',
            old_name='name',
            new_name='pi_name',
        ),
        migrations.RenameField(
            model_name='tdggrant',
            old_name='name',
            new_name='pi_name',
        ),
    ]
