# Generated by Django 5.2.5 on 2025-12-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_faculty_name_billinward_pi_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='fid',
            new_name='faculty_id',
        ),
    ]
