# Generated by Django 5.2.5 on 2025-12-10 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_fid_payment_faculty_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='faculty_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='project.faculty'),
        ),
    ]
