# Generated by Django 5.2.5 on 2025-12-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_payment_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='tds_percent',
            new_name='tds_rate',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='tax_us',
            new_name='tds_section',
        ),
    ]
