# Generated by Django 5.2.5 on 2025-12-26 11:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_tds_percent_payment_tds_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSanctionDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(help_text='e.g. 2024-25', max_length=9)),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sanctioned Amount')),
                ('project_no', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=500)),
                ('pi_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Project Sanction Distribution',
                'verbose_name_plural': 'Project Sanction Distributions',
                'ordering': ['project', 'financial_year', 'head'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='cc_email_default',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cc_email_po_store',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='other_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payee_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PROCESSED', 'Processed'), ('PAID', 'Paid')], default='PROCESSED', max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='dept',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['project'], name='project_pay_project_b63b47_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['faculty'], name='project_pay_faculty_df7fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status'], name='project_pay_payment_b0ab3a_idx'),
        ),
        migrations.AddField(
            model_name='projectsanctiondistribution',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanction_distributions', to='project.faculty', verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='projectsanctiondistribution',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanction_distributions', to='project.receipthead', verbose_name='Sanction Head'),
        ),
        migrations.AddField(
            model_name='projectsanctiondistribution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanction_distributions', to='project.project', verbose_name='Project (Short No.)'),
        ),
        migrations.AddIndex(
            model_name='projectsanctiondistribution',
            index=models.Index(fields=['project'], name='project_pro_project_2b6c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsanctiondistribution',
            index=models.Index(fields=['financial_year'], name='project_pro_financi_ec67fb_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsanctiondistribution',
            index=models.Index(fields=['head'], name='project_pro_head_id_2b1911_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectsanctiondistribution',
            unique_together={('project', 'financial_year', 'head')},
        ),
    ]
