# Generated by Django 5.2.5 on 2026-01-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_projectsanctiondistribution_payment_cc_email_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='email_sent',
        ),
        migrations.AddField(
            model_name='payment',
            name='email_sent_log',
            field=models.TextField(blank=True, help_text='Auto-filled when paymentemail is sent', null=True),
        ),
    ]
