# Generated by Django 5.2.5 on 2026-01-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_payment_email_sent_payment_email_sent_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_type', models.CharField(max_length=20)),
                ('name_of_payee', models.CharField(max_length=200)),
                ('emp_code', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('gst', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('ifsc', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pfms_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pfms_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payee',
                'verbose_name_plural': 'Payees',
                'ordering': ['name_of_payee'],
            },
        ),
    ]
