# Generated by Django 5.2.5 on 2026-01-05 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_payee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='Full bank name', max_length=200)),
                ('short_no', models.CharField(help_text='Short name / code used internally', max_length=50)),
                ('account_no', models.CharField(blank=True, help_text='Default / reference account number', max_length=50, null=True)),
                ('scheme_code', models.CharField(blank=True, help_text='Scheme code (if applicable)', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'banks',
                'ordering': ['bank_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Payment Type',
                'verbose_name_plural': 'Payment Types',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='project_pay_faculty_df7fcf_idx',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='account_no',
            new_name='payee_account_no',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='bank_name',
            new_name='payee_branch_name',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='ifsc',
            new_name='payee_ifsc',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='name_of_payee',
        ),
        migrations.AddField(
            model_name='payment',
            name='payee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='project.payee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payee_pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together={('bank_name', 'short_no')},
        ),
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='project.bank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='project.paymenttype'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payee'], name='project_pay_payee_i_6b16fd_idx'),
        ),
    ]
