# Generated by Django 5.2.5 on 2026-01-05 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_bank_paymenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payee_bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='project.bank'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='project.payee'),
        ),
    ]
