# Generated by Django 5.2.5 on 2026-01-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_payment_payee_bank_name_alter_payment_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='fy',
        ),
    ]
