# Generated by Django 5.2.5 on 2026-01-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_receipt_fy'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pi_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
