# Generated by Django 5.2.5 on 2026-01-12 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_payment_pi_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extension_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_project_extension', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='extension_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Extension Reason'),
        ),
        migrations.AddField(
            model_name='seedgrant',
            name='extended_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seedgrant',
            name='extension_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_seed_extensions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seedgrant',
            name='extension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seedgrant',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seedgrant',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('EXPIRED', 'Expired')], default='ONGOING', max_length=20),
        ),
        migrations.AddField(
            model_name='tdggrant',
            name='extended_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tdggrant',
            name='extension_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tdg_extensions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tdggrant',
            name='extension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tdggrant',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tdggrant',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('EXPIRED', 'Expired')], default='ONGOING', max_length=20),
        ),
    ]
