# Generated by Django 5.2.5 on 2026-01-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_project_extension_approved_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seedgrant',
            old_name='status',
            new_name='project_status',
        ),
        migrations.RenameField(
            model_name='tdggrant',
            old_name='status',
            new_name='project_status',
        ),
    ]
