# Generated by Django 5.2.5 on 2026-01-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_rename_status_seedgrant_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinward',
            name='bill_pdf',
            field=models.FileField(blank=True, null=True, upload_to='bill_inward_pdfs/', verbose_name='Bill PDF'),
        ),
    ]
