# Generated by Django 5.2.5 on 2026-01-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_billinward_bill_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinward',
            name='bill_pdf',
            field=models.FileField(blank=True, null=True, upload_to='bill_pdfs/', verbose_name='Bill PDF'),
        ),
    ]
