# Generated by Django 5.2.5 on 2026-01-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_billinward_bill_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration'),
        ),
    ]
