# Generated by Django 5.2.5 on 2026-01-27 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_project_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedgrant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='seed_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='project.seedgrant', to_field='short_no'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='seed_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='project.seedgrant', to_field='short_no'),
        ),
        migrations.AlterField(
            model_name='seedgrant',
            name='short_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
