# Generated by Django 5.2.5 on 2026-01-27 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_seedgrant_id_alter_commitment_seed_grant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tdggrant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='tdg_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments_tdg', to='project.tdggrant', to_field='short_no'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='tdg_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenditures_tdg', to='project.tdggrant', to_field='short_no'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_short_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tdggrant',
            name='short_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
