# Generated by Django 5.2.5 on 2026-01-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_project_id_tdggrant_id_alter_commitment_tdg_grant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=7),
        ),
    ]
