# Generated by Django 5.2.5 on 2026-01-29 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_alter_project_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='seed_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='project.seedgrant'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='tdg_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments_tdg', to='project.tdggrant'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='seed_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='project.seedgrant'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='tdg_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenditures_tdg', to='project.tdggrant'),
        ),
    ]
