# Generated by Django 5.2.5 on 2026-01-30 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_alter_commitment_seed_grant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payee',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='projectsanctiondistribution',
            name='financial_year',
            field=models.CharField(help_text='e.g. 2024-25', max_length=7, validators=[django.core.validators.RegexValidator(message='Financial year must be in format YYYY-YY, e.g. 2024-25', regex='^\\d{4}-\\d{2}$')]),
        ),
    ]
