# Generated by Django 5.2.5 on 2026-02-02 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0023_remove_payee_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='project_pay_project_b63b47_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='project',
        ),
        migrations.AddField(
            model_name='payment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['content_type', 'object_id'], name='project_pay_content_b8e601_idx'),
        ),
    ]
