# Generated by Django 5.2.5 on 2026-02-03 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_remove_payment_project_pay_project_b63b47_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='project.project'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='project.project'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
