# Generated by Django 5.2.5 on 2026-02-03 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_commitment_project_commitment_voucher_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='seed_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='project.seedgrant'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tdg_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts_tdg', to='project.tdggrant'),
        ),
    ]
