# Generated by Django 5.2.5 on 2026-02-04 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_receipt_seed_grant_receipt_tdg_grant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='project_pay_payment_b0ab3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='project_pay_payee_i_6b16fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='project_pay_content_b8e601_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='project.project'),
        ),
        migrations.AddField(
            model_name='payment',
            name='seed_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='project.seedgrant'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tdg_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='project.tdggrant'),
        ),
    ]
