# Generated by Django 5.2.5 on 2026-02-04 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsanctiondistribution',
            options={'verbose_name': 'Project Sanction Distribution', 'verbose_name_plural': 'Project Sanction Distributions'},
        ),
        migrations.RemoveIndex(
            model_name='projectsanctiondistribution',
            name='project_pro_project_2b6c9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectsanctiondistribution',
            name='project_pro_financi_ec67fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectsanctiondistribution',
            name='project_pro_head_id_2b1911_idx',
        ),
        migrations.AlterUniqueTogether(
            name='projectsanctiondistribution',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectsanctiondistribution',
            name='project_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 = Year-1, 2 = Year-2, etc.', null=True),
        ),
        migrations.AddField(
            model_name='projectsanctiondistribution',
            name='seed_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanction_distributions', to='project.seedgrant'),
        ),
        migrations.AddField(
            model_name='projectsanctiondistribution',
            name='tdg_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanction_distributions_tdg', to='project.tdggrant'),
        ),
        migrations.AlterField(
            model_name='projectsanctiondistribution',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanction_distributions', to='project.project'),
        ),
        migrations.AddConstraint(
            model_name='projectsanctiondistribution',
            constraint=models.UniqueConstraint(fields=('project', 'seed_grant', 'tdg_grant', 'financial_year', 'project_year', 'head'), name='unique_sanction_distribution'),
        ),
        migrations.RemoveField(
            model_name='projectsanctiondistribution',
            name='faculty',
        ),
    ]
