# Generated by Django 5.2.5 on 2026-02-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_alter_projectsanctiondistribution_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsanctiondistribution',
            name='project_no',
        ),
    ]
