# Generated by Django 5.2.5 on 2026-02-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_remove_projectsanctiondistribution_project_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsanctiondistribution',
            name='department',
        ),
        migrations.RemoveField(
            model_name='projectsanctiondistribution',
            name='pi_name',
        ),
        migrations.RemoveField(
            model_name='projectsanctiondistribution',
            name='project_title',
        ),
    ]
