# Generated by Django 5.2.5 on 2026-02-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_remove_projectsanctiondistribution_department_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectsanctiondistribution',
            name='unique_sanction_distribution',
        ),
        migrations.RemoveField(
            model_name='projectsanctiondistribution',
            name='seed_grant',
        ),
        migrations.RemoveField(
            model_name='projectsanctiondistribution',
            name='tdg_grant',
        ),
        migrations.AddConstraint(
            model_name='projectsanctiondistribution',
            constraint=models.UniqueConstraint(fields=('project', 'financial_year', 'project_year', 'head'), name='unique_sanction_distribution'),
        ),
    ]
