# Generated by Django 5.2.5 on 2026-02-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_remove_projectsanctiondistribution_unique_sanction_distribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoPiName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
    ]
