# Generated by Django 5.2.5 on 2026-02-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_copiname_remove_project_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copiname',
            name='faculty_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
