# Generated by Django 5.2.5 on 2026-02-10 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_alter_copiname_faculty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='copiname',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='co_pi_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_copi', to='project.copiname'),
        ),
    ]
