# Generated by Django 5.2.5 on 2026-02-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_copiname_email_alter_project_co_pi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
