# Generated by Django 5.2.5 on 2026-02-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_expenditure_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
