# Generated by Django 5.2.5 on 2026-02-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_commitment_bill_date_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='funding_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='funding_type',
            field=models.CharField(blank=True, choices=[('PROJECT', 'Project'), ('SEED', 'Seed Grant'), ('TDG', 'TDG Grant')], max_length=20, null=True),
        ),
    ]
