# Generated by Django 5.2.5 on 2026-02-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_payment_funding_id_payment_funding_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
