# Generated by Django 5.2.5 on 2026-02-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_payment_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cgst_tds',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gst_tds_type',
            field=models.CharField(blank=True, choices=[('INTRA', 'CGST 1% + SGST 1%'), ('INTER', 'IGST 2%')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='igst_tds',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sgst_tds',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
