# Generated by Django 5.2.5 on 2026-02-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_alter_payment_cgst_tds_alter_payment_gst_tds_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gst_tds_type',
            field=models.CharField(blank=True, choices=[('CGST & SGST', 'CGST 1% + SGST 1%'), ('IGST', 'IGST 2%')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='net_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
