# Generated by Django 5.2.5 on 2026-02-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_alter_payment_gst_tds_type_alter_payment_net_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gst_tds_type',
            field=models.CharField(blank=True, choices=[('CGST & SGST', 'CGST 1% + SGST 1%'), ('IGST', 'IGST 2%')], default=None, max_length=20, null=True),
        ),
    ]
