# Generated by Django 5.2.5 on 2026-02-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_alter_payment_gst_tds_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration_months',
            field=models.PositiveIntegerField(default=24, verbose_name='Duration (in months)'),
            preserve_default=False,
        ),
    ]
