# Generated by Django 5.2.5 on 2026-03-02 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_project_duration_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={},
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='date',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='head',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='project',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='seed_grant',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='tdg_grant',
        ),
        migrations.AddField(
            model_name='receipt',
            name='financial_year',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='short_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='reference_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ReceiptAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.receipthead')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='project.receipt')),
            ],
        ),
        migrations.AlterField(
            model_name='receipt',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.receiptcategory'),
        ),
    ]
