# Generated by Django 5.2.5 on 2026-03-03 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_receiptcategory_alter_receipt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='commitment_code',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='commitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='project.commitment'),
        ),
    ]
