# Generated by Django 5.2.5 on 2026-03-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_commitment_commitment_code_commitment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='commitment_code',
            field=models.CharField(editable=False, max_length=5, unique=True),
        ),
    ]
