# Generated by Django 5.2.5 on 2026-03-23 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_alter_commitment_commitment_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='short_no',
        ),
        migrations.AddField(
            model_name='receipt',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='project.project'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='seed_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_seed', to='project.seedgrant'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tdg_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_tdg', to='project.tdggrant'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('admin', 'Admin Member')], default='faculty', max_length=20),
        ),
    ]
