# Generated by Django 5.2.5 on 2026-04-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommittedPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Committed Payment',
                'verbose_name_plural': 'Committed Payments',
                'ordering': ['date'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project.payment',),
        ),
    ]
