# Generated by Django 5.2.5 on 2026-04-23 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_committedpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommittedPayment',
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty Detail', 'verbose_name_plural': 'Faculty Deatails'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
