# Generated by Django 5.2.5 on 2026-04-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0049_delete_committedpayment_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='object_value',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
