# Generated by Django 5.2.5 on 2026-04-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0050_auditlog_object_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cc_email_default',
            field=models.EmailField(blank=True, default='office.src@iith.ac.in', max_length=254, null=True),
        ),
    ]
