# Generated by Django 5.2.5 on 2026-05-07 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0051_alter_payment_cc_email_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copiname',
            options={'ordering': ['name'], 'verbose_name': 'Co-PI', 'verbose_name_plural': 'Co-PIs'},
        ),
        migrations.RenameField(
            model_name='copiname',
            old_name='faculty_id',
            new_name='co_pi_id',
        ),
        migrations.AddField(
            model_name='copiname',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_pis', to='project.project'),
        ),
        migrations.AddField(
            model_name='copiname',
            name='seed_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_pis', to='project.seedgrant'),
        ),
        migrations.AddField(
            model_name='copiname',
            name='tdg_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_pis', to='project.tdggrant'),
        ),
    ]
