# Generated by Django 5.2.5 on 2026-05-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0052_alter_copiname_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='co_pi_name',
        ),
    ]
