# Generated by Django 5.2.5 on 2026-05-07 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_remove_project_co_pi_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copiname',
            name='co_pi_id',
        ),
        migrations.AddField(
            model_name='copiname',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_pi_assignments', to='project.faculty'),
        ),
    ]
